//
//  ChatScreenIntent.swift
//  BeyondChat
//
//  Created by Mac on 12.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//

import Foundation
import Combine

class ChatScreenIntent: ObservableObject {
    
    static let sharedInstance = ChatScreenIntent()
    
    @Published var chat: Chat?
    
    private let speech = SpeechManager.sharedInstance
    private var settings: CommonSettings!
    
    func setup(settings: CommonSettings) {
        self.settings = settings
        self.setupTextLines()
    }
    
    private func setupTextLines() {
        guard let chatData = settings.chatData else { fatalError("No chat data") }
        
        do {
            let decoder = JSONDecoder()
            self.chat = try decoder.decode(Chat.self, from: chatData)
        } catch {
            print(error.localizedDescription)
        }
    }
    
    func say(this text: String) {
        speech.say(this: text)
    }
    
}
