//
//  ChatScreenView.swift
//  BeyondChat
//
//  Created by Mac on 12.08.2020.
//  Copyright (c) 2020 Lammax. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct ChatScreenView: View {
    
    @EnvironmentObject var settings: CommonSettings
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = ChatScreenIntent.sharedInstance
    
    var body: some View {
        VStack {
            TopBarView()
            Spacer()
            ChatView(chat: $intent.chat)
        }
        .onAppear {
            self.intent.setup(settings: self.settings)
        }
    }
    
}

struct TopBarView: View {

    @Environment(\.colorScheme) var colorScheme

    var body: some View {
        VStack(alignment: .center, spacing: .zero) {
            Text("Dialogue")
                .font(.title)
                .foregroundColor(textColor)
                .padding(.vertical, 10)
           
            DividerView(color: .gray)
        }
    }
    
    
    var textColor: Color {
       colorScheme == .dark ? Color.white : Color.black
    }

}

struct ChatView: View {
    
    @Binding var chat: Chat?
    
    var body: some View {
        Group {
            if chat != nil {
                VStack(alignment: .leading, spacing: 30) {
                    ForEach(chat!.lines, id: \.self) { chatLine in
                        HStack {
                            ChatBubbleView(chatLine: chatLine)
                            Spacer()
                        }
                        .padding(.horizontal, 20)
                    }
                }
            } else {
                EmptyView()
            }
        }
    }
    
}

struct ChatScreenView_Previews: PreviewProvider {
    static var previews: some View {
        ChatScreenView()
    }
}
